version: '2'

services:
    dejavu:
        build: 
            context: ./
            dockerfile: ./.docker/Dockerfile
        volumes:
            - ./app:/project/app
            - ./assets:/project/assets
            - /project/node_modules
        ports:
            - "1358:1358"